config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  
  resources :restaurants do 
    
    # add searchkick url  http://restaurants/search
    collection do
      get 'search' 
    end
    
    # nest Reviews for better db association, 
    # also provides http://restaurants/4/reviews/12 route
    resources :reviews, except: [:show, :index]
  end


  get 'pages/about'
  get 'pages/contact'
  
  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader
  
  searchkick
  
  has_many :review
  
  validates :name, :address, :phone, :website, :image, presence: true
  
  validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
    message: "must be in the format (123) 456-7890" }
  validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
    message: "must start with http:// or https://" }
  validates :address, format: { with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
    message: "must be in the format 350 Fifth Avenue, New York, NY 10118" }
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :restaurant
  
  validates :rating, :comment, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: "can only be a whole number between 1 and 5"
  }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # if a User is deleted, delete all reviews         
  has_many :reviews, dependent: :destroy        
  
  validates :first_name, :last_name, presence: true
           
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_user, except: [:index, :show, :search]


  # searchkick definition for 'search'ing
  def search
    if params[:search].present?
      @restaurants = Restaurant.search(params[:search])
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
    
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
    
    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end
    
end # class

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]  


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant_id = @restaurant.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    
    @foo = @review.restaurant_id
    
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    
    def set_restaurant
      # var restaurant_id is provided by URL, thanks to nested route definition
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
    
    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else"
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
        
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

 <!-- Latest compiled and minified JQuery -->
 <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

app/views/layouts/_deviseAlerts.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %> 

app/views/layouts/_footer.html.erb
<div class="footer">
 [<a href="http://brightidea.ventures/" target="_blank">brightidea.ventures</a>]
  <span class="glyphicon glyphicon-home" aria-hidden="true">
  </span>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Yelpdemo", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>

      <!-- Replaced the default search form block with this one -->
      <%= form_tag search_restaurants_path, method: :get, class: "navbar-form navbar-left" do %>
          <p>
            <%= text_field_tag :search, params[:search], class: "form-control" %>
            <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
          </p>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelpdemo</title>
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">

    <%= render 'layouts/deviseAlerts' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to Yelpdemo!</h1>
<h2>Creating a website much like Yelp.</h2>

app/views/pages/contact.html.erb
<h1>We would love to hear from you!</h1>
<p>Contact us at benji@benjiwright.com</p>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, :html => { multipart: true }) do |f| %>
  <% if @restaurant.errors.any? %>
     <div id="error_explanation" class= "alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control" %>
      <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %> 
  </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> 
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<div class ="jumbotron">
  <h2>Yelpdemo is <a href="http://www.yelp.com" target="_blank">Yelp</a>  knockoff...</h2>
  <h3>Check out the Ruby on Rails implementation of Yelp.
  <br>Leave reviews and ratings for your fellow foodies.</h3>
</div>

<p id="notice"><%= notice %></p>

<h1>All Restaurants</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-link" %>
<% end %>

<%= image_tag "https://console.developers.google.com/m/cloudstorage/b/yelpknockoff/o/static_images/yelp_footer.png" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-md-3">

    <%= image_tag @restaurant.image_url %>
    
    <h2>
      <%= @restaurant.name %>
    </h2>
    
    <div class="star-rating" data-score= <%= @avg_rating %> ></div> 
    <p><%= "#{@reviews.length} reviews" %></p>
    
    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>
    
    <iframe
      width="230"
      height="230"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAxMFG0-WHzd1lV9F6Bt_6SyYz_42cp0SU
        &q=<%= @restaurant.address.parameterize %>&zoom=14">
    </iframe>
    
    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>
    
    <p>
      <strong>Website:</strong>
      <%= link_to @restaurant.website, "http:\\" + @restaurant.website %>
    </p>
    <%= link_to 'Write Review',  new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  </div>
  

  <div class="col-md-9">

    <% if @reviews.blank? %>
      <h3>No reviews yet. Be the first to <%= link_to 'write one!',  new_restaurant_review_path(@restaurant) %>
      </h3>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td>
                <h4>
                  <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                </h4>
                <p><%= review.created_at.strftime("%-B %-d, %-Y") %></p>
              </td>              
              <td>
                <div class="star-rating" data-score= <%= review.rating %> ></div>
                <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
                
                <% if user_signed_in? %>
                  <% if (review.user == current_user) || (current_user.admin?) %>
                    <%= link_to "Edit", edit_restaurant_review_path(@restaurant, review) %>
                    <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %>
                  <% end %>
                <% end %>  
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %> <!-- else -->


  </div>
</div>

<%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

<script>
  $('.star-rating').raty({
    path: 'https://storage.googleapis.com/yelpknockoff/static_images/stars/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<!-- had to change this because review is nested in routes.rb -->
<!-- %= form_for(@review) do |f| %> -->

<%= form_for([@restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class= "alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>



  <div id="star-rating"></div>
  
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>


<script>
  $('#star-rating').raty({
    path: 'https://storage.googleapis.com/yelpknockoff/static_images/stars/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>


<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @restaurant.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_path(@restaurant) %>